language: generic
sudo: required
services:
  - docker 

before_install:
  - docker build -t mackinon/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mackinon/docker-react npm run test

deploy:
  provider: elasticbeanstalk 
  region: us-east-2
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: elasticbeanstalk-us-east-2-382619215543
  bucket_path: "docker-react"
  no: 
    branch: master
    
